# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'shuffle-songs' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for shuffle-songs
  pod 'SnapKit', '~> 5.0.0'

  target 'shuffle-songsTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
  end

  target 'shuffle-songsUITests' do
    inherit! :search_paths
    # Pods for testing
      pod 'Quick'
      pod 'Nimble'
  end   
       
end
